/*---------------------------------------------------------------------------*\
|                                 UEqn                                        |
|-----------------------------------------------------------------------------|
| Create the momentum equation and optionally solve it as a predictor step    |
\*---------------------------------------------------------------------------*/

    fvVectorMatrix UEqn
    (
        fvm::ddt(rho, U)
      + fvm::div(phi, U)
      + turbulence->divDevRhoReff(U)
     ==
        rho*g
      + fuelCloud.SU(U)
    );

    UEqn.relax();

    if (pimple.momentumPredictor())
    {
        solve(UEqn == -fvc::grad(p));
        K = 0.5*magSqr(U);
    }
